---
name: valorant_agents_app
description: A new Flutter application.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.13.1
  hooks_riverpod: ^0.13.1
  flutter_hooks: ^0.16.0
  flutter_svg: ^0.19.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/backgrounds/
  - assets/agents/
  - assets/abilities/
  fonts:
  - family: RobotoCondensed
    fonts:
      - asset: fonts/RobotoCondensed-Light.ttf
        weight: 300
      - asset: fonts/RobotoCondensed-Regular.ttf
        weight: 400
      - asset: fonts/RobotoCondensed-Bold.ttf
        weight: 700
  - family: Tungsten
    fonts:
      - asset: fonts/Tungsten-Medium.ttf
        weight: 500
  - family: Valorant
    fonts:
    - asset: fonts/Valorant.ttf
